routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PrincipalController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PrincipalController::class, 'principalBaterias'])->name('/');

Route::get('/teoria', [PrincipalController::class, 'teoria'])->name('teoria');

Route::get('/procedimento', [PrincipalController::class, 'procedimento'])->name('procedimento');

Route::get('/medicoes', [PrincipalController::class, 'medicoes'])->name('medicoes');

Route::get('/conclusoes', [PrincipalController::class, 'conclusoes'])->name('conclusoes');

Route::get('/principal', [PrincipalController::class, 'principal']);

Route::get('/pagina1', [PrincipalController::class, 'pagina1']);

Route::get('/pagina2', [PrincipalController::class, 'pagina2']);

app/Models/Medicoes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicoes extends Model
{
    use HasFactory;
    public function getResistenciaInternaAttribute()
    {
     return $this->resistencia_carga*($this->tensao_sem_carga/$this->tensao_com_carga - 1);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PrincipalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Medicoes;

class PrincipalController extends Controller {

    public function principalBaterias(){
        return view('principalBaterias');
    }

    public function teoria(){
        return view('teoria');
    }

    public function procedimento(){
        return view('procedimento');
    }

    public function medicoes(){
        $medicoes = Medicoes::all();
        return view('medicoes',compact('medicoes'));
    }

    public function conclusoes(){
        return view('conclusoes');
    }

    public function principal(){
        return view('principal');
    }

    public function pagina1() {
        return view('pagina1');
    }

    public function pagina2() {
        return view('pagina2');
    }

}

resources/views/conclusoes.blade.php
@extends('templates.base')
@section('conteudo')
    <main>

        <h1><em>Conclusão</em></h1>
        <hr>
        <p>Através da realização das medições, podemos compreender como a resistência interna das baterias afeta a tensão disponível. 
        <p>Observamos como o uso de um resistor auxilia na determinação dessa resistência, permitindo uma análise mais precisa do comportamento desses dispositivos em diferentes situações. Essa compreensão é fundamental para a aplicação adequada de baterias e pilhas em diversas situações.</p>
        <p>A tabela informando cada medida é uma excelente forma de apresentar os dados obtidos de maneira organizada e de fácil entendimento. Com esses resultados, identificamos possíveis variações nas medições e debater sobre o que influência essas diferenças.</p>
        <p>Neste trabalho, conseguimos demonstrar o conhecimento em conceitos importantes de eletricidade, química e resistência elétrica, além de adquirirmos habilidades práticas em medições e experimentação. Essas habilidades serão essenciais para futuros estudos e aplicações no campo da elétrica e eletrônica.</p>
        <p>Ao realizar a atividade e discutir os resultados em grupo, nós compartilhamos ideias, superamos desafios e aprendemos juntos, enriquecendo a experiência e o aprendizado.</p>
        <p><em><b>Obrigado pelo seu acesso!</b></em></p>    
    </main>
    @endsection
  @section('rodape')
    <h4>Rodapé Conclusões</h4>
    @endsection

resources/views/medicoes.blade.php
@extends('templates.base')
@section('conteudo')
    <main>
        <h1><em>Medições</em></h1>
        <hr>
        <h2>Valores obtidos:</h2>
        <table class="table table-striped table-bordered" id="tbDados">
            <thead>

           
            <tr>
                <th>Pilha/Bateria</th>
                <th>Tensão nominal (v)</th>
                <th>Capacidade de corrente</th>
                <th>Tensão sem carga (v)</th>
                <th>Tensão com carga (v)</th>
                <th>Resistência de carga (ohm)</th>
                <th>Resistência interna (ohm)</th>
            </tr>
            
            </thead>
            <tbody>
                @foreach($medicoes as $medicao)
                <tr>
                    <td>{{$medicao->pilha_bateria}}</td>
                    <td>{{number_format($medicao->tensao_nominal,1,'.','')}}</td>
                    <td>{{$medicao->capacidade_corrente}}</td>
                    <td>{{$medicao->tensao_sem_carga}}</td>
                    <td>{{$medicao->tensao_com_carga}}</td>
                    <td>{{$medicao->resistencia_carga}}</td>
                    <td>{{number_format($medicao->resistencia_interna,3,'.','')}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </main>
    @endsection
  @section('rodape')
    <h4>Rodapé medições</h4>
    @endsection

resources/views/pagina1.blade.php
@extends('templates.base')

@section('conteudo')
<h2>Página 1</h2>
<hr>
    
@endsection


@section('rodape')
<h4>Rodapé da Página 1</h4>
    
@endsection

resources/views/pagina2.blade.php
@extends('templates.base')

@section('conteudo')
<h2>Página 2</h2>
<hr>
    
@endsection


@section('rodape')
<h4>Rodapé da Página 2</h4>
    
@endsection

resources/views/principal.blade.php
@extends('templates.base')

@section('conteudo')
<h2>Página Principal</h2>
<hr>
    
@endsection


@section('rodape')
<h4>Rodapé da Página Principal</h4>
    
@endsection

resources/views/principalBaterias.blade.php
    @extends('templates.base')
    @section('conteudo')
    <main>
        <h1>Turma 2D3 - Grupo 3</h1>
        <h2>Participantes</h2>
        <hr>
        <table class="table table-striped table-bordered">
            <tr>
                <th>Matrícula</th>
                <th>Nome</th>
                <th>Função</th>
            </tr>
            <tr>
                <td>0072527</td>
                <td>Henrique de Matos</td>
                <td>Desenvolvedor CSS/HTML</td>
            </tr>
            <tr>
                <td>0072543</td>
                <td>Júlio Cézar</td>
                <td>Gerente</td>
            </tr>
            <tr>
                <td>0072538</td>
                <td>Lucas Pedro </td>
                <td>Medição das Baterias</td>
            </tr>
            <tr>
                <td>0072561</td>
                <td>Matheus Machado </td>
                <td>Medição das Baterias</td>
            </tr>
            <tr>
                <td>0073008</td>
                <td>Ramos de Jesus</td>
                <td>Desenvolvedor JavaScript / Design</td>
            </tr>
        </table>
        <img src="imgs/estudantes.jpg" width="60%" alt="Integrantes do Grupo">
    </main>
  @endsection
  @section('rodape')
    <h4>Rodapé da página principal</h4>
    @endsection

resources/views/procedimento.blade.php
@extends('templates.base')
@section('conteudo')
<body>
    <header>
        <h1>Baterias</h1>
    </header>

    <nav>
        <ul>
            <li><a href="../index.html">Voltar para página principal</a></li>
        </ul>
    </nav>

    <main>
        <h1><em>Procedimentos</em></h1>
        <hr>
        <h2>Materiais:</h2>
        <p>
            Para efetuarmos as medições foi necessário a utilização dos seguintes materiais:
        
            <p>- 1 Multímetro;</p>
            <img src="/imgs/multímetro.jpg" width="10.7%" alt="multímetro">
            <p><em>Imagem ilustrativa</em></p>
            <hr>
            <p>- 1 Resistor;</p>
            <img src="/imgs/resistor.jpg" width="15%" alt="resistor">
            <p><em>Imagem ilustrativa</em></p>
            <hr>
            <p>- 1 Caderno para anotações;</p>
            <img src="/imgs/caderno.jpg" width="13%" alt="caderno">
            <p><em>Imagem ilustrativa</em></p>
            <hr>
            <p>- Pilhas/Baterias;</p>
            <img src="/imgs/pilhasilustração.jpeg" width="13%" height="150px" alt="pilhas">
            <p><em>Imagem ilustrativa</em></p>
            
            <hr>
            <h2>Mão na Massa:</h2>
            <p>- Inicializamos a parte prática do projeto, medindo a resistência do resistor que vai ser utilizado; anotamos e partimos para os outros componentes
                (baterias). 
            <p>- Definimos com Tensão(v) a medida de tensão das baterias sem carga (resistor), usando somente o multímetro;</p>
            <p>- Tensão(e) a medida com carga, usando além do multímetro o resistor conectado nas pontas de prova para sabermos as quedas de tensões de cada componente.</p>
            </p>
        </p>
    </main>
    @endsection
  @section('rodape')
    <h4>Rodapé Procedimentos</h4>
    @endsection

resources/views/templates/base.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BateriasLaravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/estilos.css') }}">
</head>

<body>
    <div class="container-md">
        <h1>Baterias Laravel</h1>
        <hr>
        <nav>
            <ul>
                <li><a href="{{ route('/') }}">Início</a></li>
                <li><a href="{{ route('teoria') }}">Teoria</a></li>
                <li><a href="{{ route('procedimento') }}">Procedimento</a></li>
                <li><a href="{{ route('medicoes') }}">Medições</a></li>
                <li><a href="{{ route('conclusoes') }}">Conclusões</a></li>
            </ul>
        </nav>

        @yield("conteudo")
        <div class="rodape container-md">
            @yield("rodape")
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

resources/views/teoria.blade.php
    @extends('templates.base')
    @section('conteudo')
    <main>
        <h1><em>Teoria</em></h1>
        
        <hr>
        
        <h2>Pilhas:</h2>
        <p>
            Pilhas são dispositivos capazes de produzir corrente elétrica (energia elétrica) a partir de reações de oxidação e redução de componentes metálicos presentes em sua estrutura. Vale dizer que:  
            <p>- Oxidação: é a capacidade que um material apresenta de perder elétrons;</p>  
            <p>- Redução: é a capacidade que um material apresenta de ganhar elétrons.</p>  
            Assim, em uma pilha, como os elétrons partem de um componente e chegam até outro, forma-se uma corrente elétrica, que é capaz de fazer funcionar diversos dispositivos eletrônicos.
        </p>
        
        <img src="/imgs/pilhas.jpg" width="15%" alt="pilhas"> 
        
        <hr>
        
        <h2>Baterias:</h2>
        <p>Baterias são dispositivos que produzem corrente elétrica a partir de reações de oxidorredução reversíveis, ou seja, que podem ser renovadas e continuar gerando energia.</p>
        <p>As baterias são conjuntos de pilhas ligadas em série, ou seja, são dispositivos eletroquímicos nos quais ocorrem reações de oxidorredução, produzindo uma corrente elétrica. Podem ser chamadas ainda de pilhas secundárias, baterias secundárias ou acumuladores.</p>   
        <img src="/imgs/bateria.jpeg" width="370px" alt="baterias"> 
    </main>
    
</body>
</html>
@endsection
  @section('rodape')
    <h4>Rodapé Teoria</h4>
    @endsection